spring:

  profiles:
      include: oauth

  datasource:
    url: jdbc:mariadb://localhost:3306/webservice
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      
      
